###
DELETE http://localhost:8080/message/clear

> {%
 client.assert(response.status === 200)
 %}

###
GET http://localhost:8080/message/get

> {%
 client.assert(response.status === 200)
 %}

###
PUT http://localhost:8080/message/add
Content-Type: application/json

{
  "userName": "Qwe",
  "text": "Asd"
}

> {%
 client.assert(response.status === 200)
 %}

###
PUT http://localhost:8080/message/add
Content-Type: application/json

{
  "userName": "Rty",
  "text": "Fgh"
}

> {%
 client.assert(response.status === 200)
 %}

###
GET http://localhost:8080/message/get

> {%
 client.assert(response.status === 200)
 client.assert(response.body[0].userName === "Qwe")
 client.assert(response.body[0].text === "Asd")
 client.assert(response.body[1].userName === "Rty")
 client.assert(response.body[1].text === "Fgh")
 %}