###
DELETE http://localhost:8080/message/clear

> {%
 client.assert(response.status === 200)
 %}

###
GET http://localhost:8080/message/get

> {%
 client.assert(response.status === 200)
 %}

###
PUT http://localhost:8080/message/add

qwe

> {%
 client.assert(response.status === 200)
 %}

###
PUT http://localhost:8080/message/add

test

> {%
 client.assert(response.status === 200)
 %}

###
GET http://localhost:8080/message/get

> {%
 client.assert(response.status === 200)
 client.assert(response.body[0] === "qwe")
 client.assert(response.body[1] === "test")

 %}